version: "3.9"


networks:
  spc-network:
    driver: bridge

services:
#  spc-mysql:
#    image: mysql:8.0
#    command: --default-authentication-plugin=mysql_native_password
#    environment:
#      MYSQL_ROOT_PASSWORD: "root"
#    ports:
#      - "33061:3306"
#    networks:
#      - spc-network

  spc-api:
    image: spc-api
    #image: fabio/spc-api #para buscar a imagem no meu docker hub
#    environment:
#      DB_HOST: spc-mysql
    networks:
      - spc-network
#    depends_on:
#      - spc-mysql

  spc-proxy:
    build: ./nginx
    image: spc-proxy
    ports:
      - "82:80"
    networks:
      - spc-network
    depends_on:
      - spc-api

