version: "3.9"

networks:
  spc-network:
    driver: bridge

services:

  spc-api:
    image: spc-api
    networks:
      - spc-network
    volumes:
      #- /Users/user/Desktop/spc-imagens-docker:/app/imagens   # Mapeia o diretório de imagens compartilhado com o contêiner
      - C:\Users\user\Desktop\spc-imagens-docker:/app/imagens


  spc-proxy:
    build: ./nginx
    image: spc-proxy
    ports:
      - "82:80"
    networks:
      - spc-network
    depends_on:
      - spc-api
