server:
  port: 8080

printer:
  ip: localhost
  port: 18000

logging:
  file:
    name: C:\Users\user\Desktop\SPC-V2\logs\log.txt
  level:
    root: INFO

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/safeline?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Africa/Harare
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

    show-sql: true
    hibernate:
      ddl-auto: update


  

